{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeAbstractions #-}
{-# LANGUAGE TypeApplications #-}

-- | The heuristic function to pick the best update from the candidates generated by the non-deterministic backwards update semantics.
module Update.SnS.Heuristic (
    curveUpdateWithInfo,
    bestUpdate,
)
where

import AST
import Pretty
import Update.SnS
import Update.Types

curveUpdateWithInfo ::
    forall param env.
    (DiffEnv env, SelectParam param) =>
    EpicycleId ->
    EpicycleParamType param ->
    CurveState env ->
    Maybe (UpdateInfo env)
curveUpdateWithInfo epicycleId target state = do
    (cs, (depth, candidates)) <- genericCurveUpdate @param strategy epicycleId target state
    pure (UpdateInfo cs depth candidates)
  where
    strategy env expr tgt = do
        (res, depth, n) <- bestUpdateWithInfo env expr tgt
        pure (res, (depth, n))

bestUpdate ::
    ((BindableNum n)) =>
    (DiffEnv env) =>
    IEnv env ->
    AST Numbered env (SNum n) ->
    n ->
    Maybe (UpdateResult Numbered env (SNum n))
bestUpdate env expr target =
    case sortOn (rankResult expr env) (exprUpdate env expr target) of
        [] -> Nothing
        (r : _) -> Just r

bestUpdateWithInfo ::
    (BindableNum n, DiffEnv env) =>
    IEnv env ->
    AST Numbered env (SNum n) ->
    n ->
    Maybe (UpdateResult Numbered env (SNum n), EditDepth, [(Text, EditDepth)])
bestUpdateWithInfo env expr target =
    case sortOn (rankResult expr env) (exprUpdate env expr target) of
        [] -> Nothing
        ranked@(r : _) ->
            let depth = rankResult expr env r
                details = [(prettyToText res, rankResult expr env res) | res <- ranked]
             in Just (r, depth, details)
