name: Build and Cache Nix Flake

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: bristermittenmasters
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Project Binary
        run: nix build .#default --accept-flake-config

      - name: Cache Dev Environment
        run: nix develop .#default --accept-flake-config -c echo "Dev environment cached!"